"""Add TaskList model and update Task

Revision ID: 5bbe2c19a097
Revises: 8c1da3b69195
Create Date: 2026-05-03 09:23:52.334528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bbe2c19a097'
down_revision: Union[str, Sequence[str], None] = '8c1da3b69195'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_lists_id'), 'task_lists', ['id'], unique=False)
    op.add_column('tasks', sa.Column('task_list_id', sa.Integer(), nullable=True))
    op.alter_column('tasks', 'chat_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'tasks', 'task_lists', ['task_list_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.alter_column('tasks', 'chat_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('tasks', 'task_list_id')
    op.drop_index(op.f('ix_task_lists_id'), table_name='task_lists')
    op.drop_table('task_lists')
    # ### end Alembic commands ###
